name: CI

on:
  push:
    branches: [main]

jobs:
  ci:
    name: CI

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Linter
        run: |
          yarn install
          yarn lint

      - name: Build
        run: |
          yarn install
          yarn build

      # - name: Test
      #   run: |
      #     cd backend
      #     yarn install
      #     yarn test
